name: pomotasks
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.1.3
environment:
  sdk: ^3.8.0
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
# My Pomotasks dependencies
  ## Audio Player Package to play Timer Sounds
  audioplayers: ^6.4.0
  ## Flutter Bloc Package to manage state
  flutter_bloc: ^9.1.1
  ## Flutter Native Splash Package to show Splash Screen
  flutter_native_splash: ^2.4.6
  ## Flutter Screen Util Package to manage responsive UI
  flutter_screenutil: ^5.9.3
  ## Flutter SVG Package to Display SVG images
  flutter_svg: ^2.1.0
  ## Go Router Package to manage navigation in Pomotasks
  go_router: ^15.1.3
  ## Google Fonts Package to use Google Fonts in Pomotasks
  google_fonts: ^6.2.1
  ## Rename Package to rename the Dufault App Name to Pomotasks
  rename_app: ^1.6.3
  ## Salomon Bottom Bar Package to manage Bottom Navigation Bar in Pomotasks
  salomon_bottom_bar: ^3.3.2
  ## Time Package to manage Time in Pomotasks
  time: ^2.1.5
  ## Hive Package to manage Data in Pomotasks
  hive: ^2.2.3
  ## Hive Generator Package to Generate Hive Adapter
  hive_generator: ^2.0.1
  ## Hive Flutter Package to use Hive in Flutter
  hive_flutter: ^1.1.0
  ## My Pomotasks dependencies.
  get_it: ^8.0.3
<<<<<<< HEAD
  ## my Pomotasks Chart Package
  ## to manage Chart in Pomotasks
  fl_chart: ^1.0.0
=======
  ## Path Provider Package to get App Directory
  path_provider: ^2.1.5
>>>>>>> origin/Development
#End My Pomotasks dependencies.
# Dev dependencies are used to develop the package and are not required for running the app
dev_dependencies:
  # Flutter Icons Launcher Plugin to Change App Default Icon to pomodoro technique icon
  flutter_launcher_icons: "^0.14.3"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_launcher/pomodoro-technique.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # End Flutter Icons Launcher Plugin Discription.
  # The following adds the flutter_test package and the plugin for local unit testing
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    # Images Assets
    - assets/images/
    # Icons Assets
    - assets/icons/
    # Audios Assets
    - assets/audios/
  # End assets Discription.

  # An image asset can refer to one or more resolution-specific "variants", see Flutter Docs
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see Flutter Docs
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
